In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [4]:
date.head() #Orders from a ecommerce website

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
time.head() #Chatting dataset

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [12]:
date.info() #By default in pandas Date and Time are mere Stringsor Object you first need to convert them!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [13]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

###Working with the Dates

In [14]:
#Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [15]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

####1. Extract Year

In [17]:
date['date_year'] = date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
359 2019-03-23        3339       22      38       2019
81  2019-03-22        3143       25       1       2019
383 2019-11-28         820       30       6       2019
262 2018-11-14        4667        9       1       2018
184 2019-01-21        6371        7       8       2019

####2. Extract Month

In [22]:
date['date_month'] = date['date'].dt.month # but this gives the month number
date['date_month_name'] = date['date'].dt.month_name() # this gives the month name
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name
556,2019-03-14,2422,18,3,2019,3,March
54,2018-09-26,3196,29,1,2018,9,September
161,2019-03-30,7140,18,26,2019,3,March
950,2019-05-10,2137,2,10,2019,5,May
420,2018-08-07,7288,14,5,2018,8,August

####3. Extract Days

-Day number

In [27]:
date['date_day'] = date['date'].dt.day
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow
78,2019-05-28,3044,7,7,2019,5,May,28,1
355,2019-09-18,6779,10,3,2019,9,September,18,2
423,2019-08-14,5670,28,1,2019,8,August,14,2
587,2019-10-30,6153,22,6,2019,10,October,30,2
25,2018-09-14,4487,14,1,2018,9,September,14,4

-Day of the week

In [31]:
date['date_dow'] = date['date'].dt.dayofweek #Again this only provides wth the da of the wek as a number from 0 to 7
date['date_dow_name'] = date['date'].dt.day_name() #here to get name of the day we dont need to specify the dayofweek but general as day_name
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name
936,2019-08-02,2051,13,1,2019,8,August,2,4,Friday
94,2019-04-10,300,14,462,2019,4,April,10,2,Wednesday
104,2018-09-12,6134,6,1,2018,9,September,12,2,Wednesday
33,2019-07-11,3121,17,1,2019,7,July,11,3,Thursday
510,2019-04-04,5953,13,34,2019,4,April,4,3,Thursday

-Weekend?

In [32]:
#to check if the day is weekend we need to use logic and not inbuilt function
date['date_weekend?'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_weekend?
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

####4. Extract Week of the Year

In [39]:
date['date_week'] = date['date'].dt.isocalendar().week
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_weekend?,date_week
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

####5. Extract Quater

In [42]:
date['quarter'] = date['date'].dt.quarter
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_weekend?,date_week,quarter
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1

####6. Extract Semester

In [43]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1,2)
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_weekend?,date_week,quarter,semester
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1

####7. Extract Time elapsed between dates

In [44]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2025, 6, 2, 12, 36, 53, 643824)

-Time passed

In [45]:
today - date['date']

0     2001 days 12:36:53.643824
1     2483 days 12:36:53.643824
2     2414 days 12:36:53.643824
3     2116 days 12:36:53.643824
4     2339 days 12:36:53.643824
                 ...
995   2429 days 12:36:53.643824
996   2370 days 12:36:53.643824
997   2218 days 12:36:53.643824
998   2283 days 12:36:53.643824
999   2057 days 12:36:53.643824
Name: date, Length: 1000, dtype: timedelta64[ns]

-Days passed exactly

In [46]:
(today - date['date']).dt.days

0      2001
1      2483
2      2414
3      2116
4      2339
       ...
995    2429
996    2370
997    2218
998    2283
999    2057
Name: date, Length: 1000, dtype: int64

-Months passed

In [50]:
#This stuff doesn't come up at the door so need a little tweaks
#np.round((today - date['date']) / np.timedelta64(1, 'M'),0) ---> this method is discarded from the video
#therefore make a jugaad
np.round((today - date['date']).dt.days / 30.4375, 0)

0      66.0
1      82.0
2      79.0
3      70.0
4      77.0
       ...
995    80.0
996    78.0
997    73.0
998    75.0
999    68.0
Name: date, Length: 1000, dtype: float64

###Working with Time

In [51]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [52]:
time['date'] = pd.to_datetime(time['date'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [53]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second
time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [58]:
time['time'] = time['date'].dt.time
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

####Extract Time Difference

In [59]:
today - time['date']

0     4187 days 11:46:53.643824
1     4051 days 12:56:53.643824
2     4537 days 12:15:53.643824
3     3839 days 12:05:53.643824
4     4236 days 13:25:53.643824
                 ...
995   4826 days 11:46:53.643824
996   4147 days 13:22:53.643824
997   4612 days 12:59:53.643824
998   4728 days 13:02:53.643824
999   4000 days 13:11:53.643824
Name: date, Length: 1000, dtype: timedelta64[ns]

-seconds

In [60]:
(today - time['date']) /np.timedelta64(1, 's')

0      3.617992e+08
1      3.500530e+08
2      3.920410e+08
3      3.317332e+08
4      3.660388e+08
           ...
995    4.170088e+08
996    3.583490e+08
997    3.985236e+08
998    4.085462e+08
999    3.456475e+08
Name: date, Length: 1000, dtype: float64

-minutes

In [61]:
(today - time['date']) /np.timedelta64(1, 'm')

0      6.029987e+06
1      5.834217e+06
2      6.534016e+06
3      5.528886e+06
4      6.100646e+06
           ...
995    6.950147e+06
996    5.972483e+06
997    6.642060e+06
998    6.809103e+06
999    5.760792e+06
Name: date, Length: 1000, dtype: float64

-Hours

In [62]:
(today - time['date']) / np.timedelta64(1, 'h')

0      100499.781568
1       97236.948234
2      108900.264901
3       92148.098234
4      101677.431568
           ...
995    115835.781568
996     99541.381568
997    110700.998234
998    113485.048234
999     96013.198234
Name: date, Length: 1000, dtype: float64